In [0]:
import numpy as np
import pandas as pd
import json
from tqdm import tqdm
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from datetime import datetime

In [0]:
final_dataset = pd.read_csv('final_dataset.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
final_dataset.columns

Index(['Unnamed: 0', 'user_id', 'business_id', 'review_id', 'rating', 'date',
       'useful_x', 'funny_x', 'cool_x', 'text', 'name_x', 'address', 'city',
       'state', 'postal_code', 'latitude', 'longitude', 'stars',
       'review_count_x', 'category', 'RestaurantsTakeOut',
       'RestaurantsPriceRange2', 'GoodForKids', 'HasTV',
       'RestaurantsGoodForGroups', 'RestaurantsReservations', 'WiFi',
       'RestaurantsAttire', 'Alcohol', 'OutdoorSeating', 'RestaurantsDelivery',
       'BikeParking', 'average_stars', 'compliment_cool', 'compliment_cute',
       'compliment_funny', 'compliment_hot', 'compliment_list',
       'compliment_more', 'compliment_note', 'compliment_photos',
       'compliment_plain', 'compliment_profile', 'compliment_writer', 'cool_y',
       'elite', 'fans', 'friends', 'funny_y', 'name_y', 'review_count_y',
       'useful_y', 'yelping_since'],
      dtype='object')

In [0]:
final_dataset.city.unique()

array(['Las Vegas', 'Phoenix', 'Toronto'], dtype=object)

# Select only 'Las Vegas' and 'Toronto' cities 

In [0]:
val = ["Las Vegas","Toronto"]

In [0]:
sample = final_dataset.loc[final_dataset['city'].isin(val) ]

In [0]:
sample.to_csv("clean_dataset.csv")

In [0]:
sample.isnull().sum()

Unnamed: 0                       0
user_id                          0
business_id                      0
review_id                        0
rating                           0
date                             0
useful_x                         0
funny_x                          0
cool_x                           0
text                             0
name_x                           0
address                       2222
city                             0
state                            0
postal_code                    405
latitude                         0
longitude                        0
stars                            0
review_count_x                   0
category                         0
RestaurantsTakeOut               0
RestaurantsPriceRange2           0
GoodForKids                      0
HasTV                            0
RestaurantsGoodForGroups         0
RestaurantsReservations          0
WiFi                             0
RestaurantsAttire                0
Alcohol             

In [0]:
len(sample.columns)

53

In [0]:
sample.loc[(sample.RestaurantsTakeOut == 'False'),'RestaurantsTakeOut'] = False
sample.loc[(sample.RestaurantsTakeOut == 'True'),'RestaurantsTakeOut'] = True
sample.loc[(sample.RestaurantsTakeOut == 'None'),'RestaurantsTakeOut'] = False
sample['RestaurantsTakeOut'].fillna(False, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6287: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [0]:
sample['RestaurantsPriceRange2'] = sample['RestaurantsPriceRange2'].astype(str)

In [0]:
sample.loc[(sample.RestaurantsPriceRange2 == '2.0'),'RestaurantsPriceRange2'] = '2'
sample.loc[(sample.RestaurantsPriceRange2 == '3.0'),'RestaurantsPriceRange2'] = '3'
sample.loc[(sample.RestaurantsPriceRange2 == '1.0'),'RestaurantsPriceRange2'] = '1'
sample.loc[(sample.RestaurantsPriceRange2 == '4.0'),'RestaurantsPriceRange2'] = '4'
sample['RestaurantsPriceRange2'].fillna('None', inplace=True)
sample.loc[(sample.RestaurantsPriceRange2 == 'nan'),'RestaurantsPriceRange2'] = 'None'

In [0]:
sample.RestaurantsPriceRange2.unique()

array(['2', '1', '3', 'None', '4'], dtype=object)

In [0]:
sample.GoodForKids.unique()

array([ True, False])

In [0]:
sample.loc[(sample.GoodForKids == 'False'),'GoodForKids'] = False
sample.loc[(sample.GoodForKids == 'True'),'GoodForKids'] = True
sample.loc[(sample.GoodForKids == 'None'),'GoodForKids'] = False
sample['GoodForKids'].fillna(False, inplace=True)

In [0]:
sample.HasTV.unique()

array([False,  True])

In [0]:
sample.loc[(sample.HasTV == 'False'),'HasTV'] = False
sample.loc[(sample.HasTV == 'True'),'HasTV'] = True
sample.loc[(sample.HasTV == 'None'),'HasTV'] = False
sample['HasTV'].fillna(False, inplace=True)

In [0]:
sample.RestaurantsGoodForGroups.unique()

array([ True, False])

In [0]:
sample.loc[(sample.RestaurantsGoodForGroups == 'False'),'RestaurantsGoodForGroups'] = False
sample.loc[(sample.RestaurantsGoodForGroups == 'True'),'RestaurantsGoodForGroups'] = True
sample.loc[(sample.RestaurantsGoodForGroups == 'None'),'RestaurantsGoodForGroups'] = False
sample['RestaurantsGoodForGroups'].fillna(False, inplace=True)

In [0]:
sample.RestaurantsReservations.unique()

array([False,  True])

In [0]:
sample.loc[(sample.RestaurantsReservations == 'False'),'RestaurantsReservations'] = False
sample.loc[(sample.RestaurantsReservations == 'True'),'RestaurantsReservations'] = True
sample.loc[(sample.RestaurantsReservations == 'None'),'RestaurantsReservations'] = False
sample['RestaurantsReservations'].fillna(False, inplace=True)

In [0]:
sample.WiFi.unique()

array(['no', 'free', 'None', 'paid'], dtype=object)

In [0]:
print(sample.WiFi[0])
val = sample.WiFi[0]
val = val.replace("'","")
sample['WiFi'] = sample['WiFi'].str.replace("'","")

In [0]:
sample.loc[(sample.WiFi == 'uno' ),'WiFi'] = 'no'
sample.loc[(sample.WiFi == 'ufree' ),'WiFi'] = 'free'
sample.loc[(sample.WiFi == 'upaid' ),'WiFi'] = 'paid'
sample['WiFi'].fillna('None', inplace=True)

In [0]:
sample.RestaurantsAttire.unique()

array(['casual', 'None', 'dressy', 'formal'], dtype=object)

In [0]:
sample['RestaurantsAttire'] = sample['RestaurantsAttire'].str.replace("'","")

In [0]:
sample.loc[(sample.RestaurantsAttire == 'ucasual' ),'RestaurantsAttire'] = 'casual'
sample.loc[(sample.RestaurantsAttire == 'udressy' ),'RestaurantsAttire'] = 'dressy'
sample.loc[(sample.RestaurantsAttire == 'uformal' ),'RestaurantsAttire'] = 'formal'
sample['RestaurantsAttire'].fillna('None', inplace=True)

In [0]:
sample.Alcohol.unique()

array(['beer_and_wine', 'full_bar', 'None'], dtype=object)

In [0]:
sample['Alcohol'] = sample['Alcohol'].str.replace("'","")

In [0]:
sample.loc[(sample.Alcohol == 'ubeer_and_wine' ),'Alcohol'] = 'beer_and_wine'
sample.loc[(sample.Alcohol == 'ufull_bar' ),'Alcohol'] = 'full_bar'
sample.loc[(sample.Alcohol == 'unone' ),'Alcohol'] = 'None'
sample.loc[(sample.Alcohol == 'none' ),'Alcohol'] = 'None'
sample['Alcohol'].fillna('None', inplace=True)

In [0]:
sample.OutdoorSeating.unique()

array([False,  True])

In [0]:
sample.loc[(sample.OutdoorSeating == 'False'),'OutdoorSeating'] = False
sample.loc[(sample.OutdoorSeating == 'True'),'OutdoorSeating'] = True
sample.loc[(sample.OutdoorSeating == 'None'),'OutdoorSeating'] = False
sample['OutdoorSeating'].fillna(False, inplace=True)

In [0]:
sample.RestaurantsDelivery.unique()

array([False,  True])

In [0]:
sample.loc[(sample.RestaurantsDelivery == 'False'),'RestaurantsDelivery'] = False
sample.loc[(sample.RestaurantsDelivery == 'True'),'RestaurantsDelivery'] = True
sample.loc[(sample.RestaurantsDelivery == 'None'),'RestaurantsDelivery'] = False
sample['RestaurantsDelivery'].fillna(False, inplace=True)

In [0]:
sample.BikeParking.unique()

array([False,  True])

In [0]:
sample.loc[(sample.BikeParking == 'False'),'BikeParking'] = False
sample.loc[(sample.BikeParking == 'True'),'BikeParking'] = True
sample.loc[(sample.BikeParking == 'None'),'BikeParking'] = False
sample['BikeParking'].fillna(False, inplace=True)

In [0]:
len(sample.columns)

53

In [0]:
sample.drop(columns=['WifiNew','Wifi'],inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
sample.to_csv("nan_clean_dataset.csv")

In [0]:
nan_clean_dataset = pd.read_csv('nan_clean_dataset.csv')